version: '3'

services:
  
  elasticsearch:
    image: elasticsearch:5.6
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "9200:9200"
    depends_on:
      - db
      - elasticsearch